[package]
name = "ocular"
authors = ["Collin Brittain"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.19", features = ["executor"] }
octocrab = "0.15.3"
rand = "0.8.4"
reqwest = { version = "0.11.8", features = ["json"] }
serde = "1.0.133"
serde_json = "1.0.78"
thiserror = "1.0.30"
url = "2.2.2"
