[package]
name = "ocular"
description = "A client library Cosmos SDK chains with chain registry interaction"
authors = ["Collin Brittain"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/PeggyJV/ocular"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assay = "0.1"
bip32 = "0.3.0"
futures = { version = "0.3.19", features = ["executor"] }
octocrab = "0.15.3"
rand = "0.8.4"
reqwest = { version = "0.11.8", features = ["json"] }
serde = "1.0.133"
serde_json = "1.0.78"
tendermint-rpc = { version = "0.23.5", features = ["http-client"] }
signatory = "0.24.0"
thiserror = "1.0.30"
tiny-bip39 = "0.8.2"
url = "2.2.2"
