[package]
name = "ocular"
description = "A client library for Cosmos SDK chains"
authors = ["Collin Brittain", "Phil Bal"]
version = "1.0.0-alpha"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/PeggyJV/ocular"
readme = "README.md"

[package.metadata.cargo-udeps.ignore]
normal = ["assay"]

[dependencies]
assay = "0.1"
bech32 = "0.9"
bip32 = "0.3"
# This explicit cosmos-sdk-proto import shouldn't be needed because cosmrs exposes it,
# but for some reason the cosmos module query_client rust modules aren't importable through
# cosmrs without this.
cosmos-sdk-proto = "0.12.0"
cosmrs = {version = "0.7.0", features = ["dev"] }
eyre = "0.6.8"
futures = { version = "0.3.19", features = ["executor"] }
k256 = { version = "0.10.2", features = ["pem"] }
http = "0.2"
pkcs8 = "0.8"
rand = "0.8.4"
rand_core = "0.6.3"
reqwest = { version = "0.11.8", features = ["json"] }
serde = "1.0.133"
serde_json = "1.0.78"
signatory = "0.24"
thiserror = "1.0"
tendermint-rpc = "0.23.7"
tonic = { version = "0.7.2", features = ["transport"] }
url = "2.2.2"
tendermint-proto = "0.23.5"
tokio = "1.17.0"
prost-types = "0.10.1"
prost = "0.10.4"
toml = "0.5.8"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
async-trait = "0.1.56"

[features]

[dev-dependencies]
rand = "0.8.5"
